title: "Archipelago Art"
remote_theme: just-the-docs/just-the-docs
color_scheme: archipelago-light
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
